# Generated by Django 4.2.6 on 2023-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="description",
            field=models.TextField(blank=True, max_length=119),
        ),
    ]
